### ISSUE TITLE
选择视频速率后 url解析出错

### ISSUE THREAD

**Issue by ihxjie** [ZhyMC/chaoxing-xuexitong-autoflush#10]
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at courselist.getList (C:\Users\xingj\chaoxing-xuexitong-autoflush\courselist.js:15:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async CoursePicker.getAllCourses (C:\Users\xingj\chaoxing-xuexitong-autoflush\coursepicker.js:18:13)
    at async CoursePicker.pick (C:\Users\xingj\chaoxing-xuexitong-autoflush\coursepicker.js:56:3)
    at async start (C:\Users\xingj\chaoxing-xuexitong-autoflush\main.js:39:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by Constellation39** [comment]
问题可能已经解决， 请尝试最新版本
