### ISSUE TITLE
选择刷课速率后报错

### ISSUE THREAD

**Issue by EachinChung** [ZhyMC/chaoxing-xuexitong-autoflush#12]
✔ 请输入视频刷课速率(不填默认为2) … 
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at courselist.getList (/Users/eachin/Desktop/chaoxing-xuexitong-autoflush/courselist.js:15:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async CoursePicker.getAllCourses (/Users/eachin/Desktop/chaoxing-xuexitong-autoflush/coursepicker.js:18:13)
    at async CoursePicker.pick (/Users/eachin/Desktop/chaoxing-xuexitong-autoflush/coursepicker.js:56:3)
    at async start (/Users/eachin/Desktop/chaoxing-xuexitong-autoflush/main.js:39:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by Constellation39** [comment]
问题可能已经解决，请尝试最新版本

**Comment by EachinChung** [comment]
已解决，谢谢
