### ISSUE TITLE
大大，Linux里面怎么运行啊

### ISSUE THREAD

**Issue by litengde** [ZhyMC/chaoxing-xuexitong-autoflush#16]
root@OpenWrt:~# cd chaoxing-xuexitong-autoflush-master
root@OpenWrt:~/chaoxing-xuexitong-autoflush-master# node mian.js
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/root/chaoxing-xuexitong-autoflush-master/mian.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by ZhyMC** [comment]
main拼错了哦，按照教程里的npm start运行就不会错误了。
或者你用node main也能启动。

**Comment by litengde** [comment]
(提示:若你不是win系统,可以打开目录下的verifycode.png)
? 已弹出验证码,请在这输入验证码 › events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ '/root/chaoxing/verifycode.png' ]
}
这是验证码，直接抛出错误了

**Comment by ZhyMC** [comment]
应该是尝试打开你linux下的图片查看器失败了，xdg-open这个命令不存在，抛出异常没有捕捉就直接结束了任务

**Comment by litengde** [comment]
> 应该是尝试打开你linux下的图片查看器失败了，xdg-open这个命令不存在，抛出异常没有捕捉就直接结束了任务

那这个怎么解决呀

**Comment by ZhyMC** [comment]
我提交了一个commit，应该解决了。你git pull，然后再打开试试

**Comment by litengde** [comment]
属实不太会玩linux，我用node main能打开，但弹不出验证码，用npm就提示not found

**Comment by ZhyMC** [comment]
看起来你的图片浏览器存在问题，我使用的是跨平台的图片打开，如果linux有安装图形界面的话，理论上是可以自动打开的。

**Comment by litengde** [comment]
没图形界面，我在路由器的openwrt里面弄得

**Comment by JK-Love** [comment]
不会玩linux你就装win上呗  不是有教程吗

**Comment by litengde** [comment]
> 不会玩linux你就装win上呗 不是有教程吗

我弄了个N1,打算在上面挂着刷课

**Comment by ZhyMC** [comment]
> 没图形界面，我在路由器的openwrt里面弄得

没有图形界面的话，只能手动打开验证码输入。那个报错和我使用的打开图片的模块有关，我提交了最新的commit，你可以再测试一下。

**Comment by JK-Love** [comment]
我还没测试  这个章节测试答案正确率怎么样

**Comment by ZhyMC** [comment]
> 我还没测试 这个章节测试答案正确率怎么样

都是靠题库的，如果题库里有任何一题没找到都会跳过测验。如果全找到了才会自动过测验。

**Comment by ZhyMC** [comment]
用的人越多题库越强大，数据库是MongoDB。

**Comment by JK-Love** [comment]
> 用的人越多题库越强大，数据库是MongoDB。

不调用外部API吗 全靠共享题库吗

**Comment by ZhyMC** [comment]
> > 用的人越多题库越强大，数据库是MongoDB。
> 
> 不调用外部API吗 全靠共享题库吗

实际上两者都有，策略是外部API找到了就会存到题库里，外部API挂了，题库也能自己继续维持共享工作。上传和下载题目都没问题。

**Comment by litengde** [comment]
感谢大大

**Comment by ZhyMC** [comment]
解决了吗

**Comment by aurorataro** [comment]
> 属实不太会玩linux，我用node main能打开，但弹不出验证码，用npm就提示not found
你是用的是阿里云或者腾讯云服务器吗？现在据我所知这两个服务器都被超星屏蔽了，我用香港代理访问正常。
