### ISSUE TITLE
运行环境有什么版本要求吗

### ISSUE THREAD

**Issue by myitmx** [ZhyMC/chaoxing-xuexitong-autoflush#28]
我的运行环境
centos 7.4
node v6.17.1
npm  v3.10.10

运行报错
```
/root/chaoxing-xuexitong-autoflush/main.js:15
async function getUser(cookie){
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

```

**Comment by Constellation39** [comment]
使用node 12以上可以规避这些问题
