### ISSUE TITLE
TypeError: Cannot read property 'readFile' of undefined

### ISSUE THREAD

**Issue by Hueiisgod** [ZhyMC/chaoxing-xuexitong-autoflush#34]
以下是第一次使用时npm start后全部输出，操作系统linuxmint19,
不太懂ｊｓ，还是请原作者亲自帮忙吧。npm是apt安装的，应该是最新的了

"> chaoxing@1.0.0 start /home/spock/chaoxing-xuexitong-autoflush
"> node main.js

版权声明:
作者: Wyatt Zheng
邮箱: yuxon@qq.com

本作品仅提供学习及研究程序原理用途

TypeError: Cannot read property 'readFile' of undefined
    at Config.read (/home/spock/chaoxing-xuexitong-autoflush/config.js:36:28)
    at start (/home/spock/chaoxing-xuexitong-autoflush/main.js:31:50)
    at Object.<anonymous> (/home/spock/chaoxing-xuexitong-autoflush/main.js:73:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)

**Comment by Constellation39** [comment]
用node -v查看nodejs版本最好保持在12.18.1及以上

**Comment by Hueiisgod** [comment]
是的，确实是版本低的问题，现在升级后运行没问题了。这个脚本说不定到以后也还是有用呢，现在也不确定下半年能不能正常上学。
